### ISSUE TITLE
file permissions with symfony

### ISSUE THREAD

**Issue by dbu** [eXistenZNL/Docker-Webstack#44]
thanks for this neat stack! i needed an all-in-one docker stack for azure webapps (not my choice :-D) and yours does the trick.

i work with symfony, which uses the `bin/console` cli script to run systems tasks. 

your dockerfile creates the `php` user for php-fpm as system user. this means i can't run a shell as that user. i found that locally i can run `docker exec` with `-u php` and get a shell with the php user.

but on azure, the way to connect to the application is setting up [sshd](https://learn.microsoft.com/en-gb/azure/app-service/configure-custom-container?tabs=alpine&pivots=container-linux#enable-ssh). and then i will be root and can't `su php` because that user is a system user. is there a security concern making `php` an interactive user, or do you have some other idea how to handle this?

**Comment by eXistenZNL** [comment]
Oof, not sure why you wouldn't be able to su to a system user.

Is it maybe because no shell is set? Can you specify the shell with `su - php -s /bin/sh`?

The PHP user is a system user, this is how the separation between system and normal users is meant. This should not be changed because Microsoft added extra requirements on top...

**Comment by dbu** [comment]
thank you, that is a good idea. and i agree we should not change the stack for weird edge cases.
